# Generated by Django 3.2.16 on 2023-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocollection',
            options={'permissions': (('access_geocollection', 'Can view geocollection'),)},
        ),
    ]
